"""Add learning_style column to Students model

Revision ID: 03c152d67cc3
Revises: dbd0ac381df5
Create Date: 2025-02-02 19:13:37.564288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c152d67cc3'
down_revision = 'dbd0ac381df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_style', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('learning_style')

    # ### end Alembic commands ###
