"""Initial migration for Supabase

Revision ID: 162785a75d99
Revises: 
Create Date: 2025-02-04 21:20:57.664869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162785a75d99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=False))

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=255), nullable=False))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_style', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fname')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('learning_style')

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_column('topic')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('score')

    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
