"""changed column types for Students

Revision ID: 19808544b8db
Revises: 03c152d67cc3
Create Date: 2025-02-03 20:47:26.120784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19808544b8db'
down_revision = '03c152d67cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('preferred_topics',
               existing_type=mysql.JSON(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('strengths',
               existing_type=mysql.JSON(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('weaknesses',
               existing_type=mysql.JSON(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('learning_style',
               existing_type=mysql.JSON(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('learning_style',
               existing_type=sa.String(length=50),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('weaknesses',
               existing_type=sa.String(length=50),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('strengths',
               existing_type=sa.String(length=50),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.alter_column('preferred_topics',
               existing_type=sa.String(length=50),
               type_=mysql.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
