"""added intro competencies to student progress

Revision ID: 23a7f91849d3
Revises: 5d729b18afbc
Create Date: 2025-03-31 18:20:15.827487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a7f91849d3'
down_revision = '5d729b18afbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('python_intro_competencies', sa.JSON(), nullable=True))
        batch_op.alter_column('topic',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('topic',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('python_intro_competencies')

    # ### end Alembic commands ###
