"""Change interests back to JSON

Revision ID: 318588098598
Revises: 750e436ac0e8
Create Date: 2025-04-13 23:36:13.784752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318588098598'
down_revision = '750e436ac0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'interests',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.JSON(),
            existing_nullable=True,
            postgresql_using="to_jsonb(string_to_array(interests, ','))"  # Transform comma-separated strings to JSON array
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'interests',
            existing_type=sa.JSON(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
            postgresql_using="array_to_string(interests, ',')"  # Convert JSON array back to a comma-separated string
        )
    # ### end Alembic commands ###