"""added learning pace to student

Revision ID: 47d6ef7088c1
Revises: 095ea01f1272
Create Date: 2025-02-22 18:58:17.413204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6ef7088c1'
down_revision = '095ea01f1272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_pace', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('learning_pace')

    # ### end Alembic commands ###
