"""Add vector_store_file_id column into coursecontent

Revision ID: 5d729b18afbc
Revises: 566143508ee1
Create Date: 2025-03-12 19:00:27.795802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d729b18afbc'
down_revision = '566143508ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_store_file_id', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.drop_column('vector_store_file_id')

    # ### end Alembic commands ###
