"""Fix foreign key reference in Students model

Revision ID: 737fcc0cbc9a
Revises: 19808544b8db
Create Date: 2025-02-03 21:27:12.545079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737fcc0cbc9a'
down_revision = '19808544b8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
