"""removed quiz id from student progress

Revision ID: 79948cbaad81
Revises: bd58632f6688
Create Date: 2025-04-02 23:14:15.783990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79948cbaad81'
down_revision = 'bd58632f6688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_constraint('student_progress_quiz_id_fkey', type_='foreignkey')
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('student_progress_quiz_id_fkey', 'quizzes', ['quiz_id'], ['quiz_id'])

    # ### end Alembic commands ###
