"""added score, time spent, and attempt date to quizzes

Revision ID: bd58632f6688
Revises: 3f89661c8e34
Create Date: 2025-04-02 23:06:06.246750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd58632f6688'
down_revision = '3f89661c8e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('time_spent', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('time_spent')
        batch_op.drop_column('attempt_date')

    # ### end Alembic commands ###
