"""Change teacher classes to JSON

Revision ID: c0ddd74ce87d
Revises: f78ae708e008
Create Date: 2025-02-09 19:14:38.268898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ddd74ce87d'
down_revision = 'f78ae708e008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('classes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using='classes::json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('classes',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               nullable=False,
               postgresql_using='classes::text')

    # ### end Alembic commands ###
