"""classifcation and interests

Revision ID: f38ac238e48b
Revises: 23a7f91849d3
Create Date: 2025-04-01 09:45:01.107477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38ac238e48b'
down_revision = '23a7f91849d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('classification', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('classification')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
