"""Quizzes change

Revision ID: fcb8202e5f46
Revises: 8890efda619a
Create Date: 2025-02-20 21:00:59.382413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb8202e5f46'
down_revision = '8890efda619a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courses_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'courses', ['courses_id'], ['id'])

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_column('action')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('courses_id')

    # ### end Alembic commands ###
